name: SBURBSim_Dart_Edition
description: A no-longer-javascript SBRUB Story and Original Character generator.
version: 0.0.1
author: jadedResearcher, ParadoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: any
  petitparser: any
  xml: any
  source_map_stack_trace: any
  archive: any
  build_config: any


dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0

#transformers:
#- $dart2js:
#    sourceMaps: true
#    commandLineOptions: [--fast-startup]
#    $exclude: ["web/manifest/bundlebuilder.dart", "web/manifest/sourcemanifest.txt"]

web:
  compiler:
    debug: dartdevc

